### ISSUE TITLE
Document update process for new Cottontail API

### ISSUE THREAD

**Issue by silvanheller** [Spiess/cottontaildb-python-client#12]
It would be good to have in the README a brief documentation on the steps needed to update when new API versions are up. The reason i'm bringing this up is that Cottontail is upgrading to 0.14.0 and it would be good to update the Python Client in due time.

**Comment by Spiess** [comment]
This is being addressed by 7ad552b10b41057f64b1df1a48ef2906eae01385 and will be merged with the CottontailDB proto version upgrade, because I was not careful enough to separate this change onto its own branch.
