### ISSUE TITLE
Import errors for generated cottontail_pb2_grpc and cottontail_pb files when performing simple insertions

### ISSUE THREAD

**Issue by Aece96** [Spiess/cottontaildb-python-client#15]
Hello dear developers

I have installed the cottontaildb-python-client according to the instructions in the README of the repository. However, when attempting to perform simple insertions in CottontailDB through a Python script, I am getting import errors related to the generated cottontail_pb2_grpc and cottontail_pb files created by the proto file.

I also adapted the import statement in those as suggested in the development section.

![grafik](https://user-images.githubusercontent.com/45922740/226323723-9cdd0694-9fd1-4030-aba9-5f9e5ef335f0.png)
![grafik](https://user-images.githubusercontent.com/45922740/226323935-b4ec7a61-dbb9-4a39-9e4c-5584e8cbd7a2.png)
![grafik](https://user-images.githubusercontent.com/45922740/226324138-8da0d9e9-8673-4441-ab1c-2b772da17c4b.png)

I don t really understand how the import error can go wrong especially since the code I am trying to run and the code of the example snippet throw the same error.

Thank you very much, looking forward to hear from you.
Best regards Cyrill

**Comment by lucaro** [comment]
Looks like this client is not up to date. Assuming you are using the latest version of Cottontail DB, you would need to use the `0.15.0` version of the driver. If I see this correctly, the python client still uses `0.14.0`, which is no longer compatible. @Spiess could you please check and update accordingly?

**Comment by Spiess** [comment]
The client should still be up to date, according to the [compatibility matrix](https://github.com/vitrivr/cottontaildb/wiki/Compatibility-Matrix) driver `0.14.0 `is the newest version supported by Cottontail DB.
I have confirmed this by running all tests with Cottontail DB version `0.15.2`.

Just to be safe, I have also created a preparatory branch for driver version `0.15.0` and have confirmed that it uses functions not yet implemented in the newest version of Cottontail DB.

It looks to me like the issue is a Python import problem unrelated to Cottontail DB. How have you installed the Python client exactly? Did you install it from PyPI, or the git repository?

**Comment by Aece96** [comment]
Thank you for the fast answer.At the Moment the version I use was installed via PyPI aka I used a pip install. However, I also tried different approaches to execute the example code by cloning the repository and executing the Setup.py file or the requirements.txt file of the Folder which resulted in messages that the required grpcio Tools were set up already.Gesendet von Mail für Windows Von: Florian SpiessGesendet: Montag, 20. März 2023 19:19An: Spiess/cottontaildb-python-clientCc: Aece96; AuthorBetreff: Re: [Spiess/cottontaildb-python-client] Import errors for generated cottontail_pb2_grpc and cottontail_pb files when performing simple insertions (Issue #15) The client should still be up to date, according to the compatibility matrix driver 0.14.0 is the newest version supported by Cottontail DB.I have confirmed this by running all tests with Cottontail DB version 0.15.2.Just to be safe, I have also created a preparatory branch for driver version 0.15.0 and have confirmed that it uses functions not yet implemented in the newest version of Cottontail DB.It looks to me like the issue is a Python import problem unrelated to Cottontail DB. How have you installed the Python client exactly? Did you install it from PyPI, or the git repository?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Spiess** [comment]
Unfortunately I am unable to reproduce the issue with the given information.
Could you provide steps to reliably trigger the issue?

**Comment by silvanheller** [comment]
@Aece96 Specifically, it would be helpful if you would execute your example-code in a separate folder outside the repository, this might help eliminating some of the possible errors.

I can also confirm that the example code runs through without issues on the newest cottontail version locally.

**Comment by silvanheller** [comment]
@Aece96 additionally, you can try upgrading to the newest version, which might address your specific issue.

**Comment by Aece96** [comment]
Thank you for the responses, it seems there is a problem with my device in this regard I am currently looking into more detail.
