### ISSUE TITLE
"Where" argument in CottontailDB client 

### ISSUE THREAD

**Issue by Aece96** [Spiess/cottontaildb-python-client#17]
I managed to get data into a running cottontaildb Instance but when trying to use the "query" function of the CottontailDB Client class I cant figure out how to pass a valid argument.

Do you have a sample code of some sort or a hint how it can be used properly?

Thank you very much
Best regards
Cyrill

**Comment by silvanheller** [comment]
You can have a look at one of the tests which queries: https://github.com/Spiess/cottontaildb-python-client/blob/4bd479f378f8b10f54e6317107c35717acb2b07e/tests/test_cottontaildb_client.py#L238

For more examples on how to use the cottontail proto api, have a look at the cottontaildb-examples repo: https://github.com/vitrivr/cottontaildb-examples

e.g.: https://github.com/vitrivr/cottontaildb-examples/blob/583a133c3d39034862fa88cbfa4e14d9f2b09720/src/main/java/org/vitrivr/cottontail/Examples.java#L187

**Comment by silvanheller** [comment]
We've added a convenience-method to the client in #18 which resolves this issue
