### ISSUE TITLE
Primary key flag in column definition seems to have no effect

### ISSUE THREAD

**Issue by ronic09** [Spiess/cottontaildb-python-client#5]
Hello! I am using your client for my master thesis. Thank you for your work!
It seems to me that the primary flag in the column definition of an entity has no effect.
It is possible to insert multiple entries with the same string ID into an entity with primary key set for the column.
Furthermore, the CLI command "entity about schema entity" does not list primary information for the columns. 

What am I doing wrong?
Many thanks,
Simon

**Comment by Spiess** [comment]
Thanks for your feedback!

Unfortunately, as far as I am aware, Cottontail DB does not yet respect the primary key property, even though it is defined in its gRPC protocol. The information is already sent from the Python client, so as soon as Cottontail DB implements this feature it should work.

**Comment by ronic09** [comment]
thank you for your reply!
