### ISSUE TITLE
Not all elements get returned in select statement

### ISSUE THREAD

**Issue by ronic09** [Spiess/cottontaildb-python-client#6]
Hello!
I am very sorry to bother you again. I am faced with some strange behaviour that I don't really understand.
If I do a select where query in cottontail, with a list of string literals, it does not return all the elements that are actually present in the DB. If I do the same query for each string literal separately I get all of the elements.
I strongly suspect that the problem is somehow related to the size of the return value.  I played with different config parameters for cottontail (config.json) but it did not really help.

Procedure to replicate: IMPORTANT: I have sent you the files per E-Mail)
1) use attached cottontail_client (it contains the select statements used in  "read_example.py")
2) init cottontail with: "cottontaildb_init_example.py"
3) import "warren.alcd_db_new.feature_vectors_inceptionv3.proto" to cottontail
4) run "read_example.py" 

Please let me know if I should rather report this issue in the cottontail repository.

Thank you so much for your help!!!
Best, Simon

**Comment by Spiess** [comment]
Hi, the problem is, that the results are returned in multiple messages and you are discarding all except the first one in line 63 of our `read_example.py`: `results = MessageToDict(list(results)[0])`

The following snippet would fix your problem:
```python
results = [MessageToDict(element) for element in results]
results = [t for message in results for t in message['tuples']]
```
